### ISSUE TITLE
Control?

### ISSUE THREAD

**Issue by chx** [falk0069/sony-pm-alt#1]
You can also control your camera with the original app on a tablet. Have you tried reversing that? Ultimately getting an UVC device would be the best but I understand that's perhaps a stretch.

**Comment by falk0069** [comment]
Hi Chx,

I'm not sure what you are asking.  Really all the sony-pm-alt does is listen on the network for when a camera is put into ptp-ip mode.  It then calls the gphoto program to do the file transferring.  Have you tried just using gphoto directly?  It has control functions you can call.  I have not played around with it at all with my camera, though.

Let me know a bit more what you want to do and I will see if I can help.

Thanks
--Andy

**Comment by chx** [comment]
I think I want http://gphoto-software.10949.n7.nabble.com/use-camera-as-a-webcam-tp4240p15632.html .
