### ISSUE TITLE
Can't send photo with a DSC-HX60V

### ISSUE THREAD

**Issue by nicolaselie** [falk0069/sony-pm-alt#2]
Hello,

Thanks for sharing your work ! I recently bought a Sony DSC-HX60V and tried your program to send photos via wifi.
I managed to get the GUID (the record from wireshark seems to be quite similar to yours) but I am not able to send any picture.
Maybe it's a gphoto2 issued. However, I used the latest version of gphoto2 (gphoto2 2.5.9.1) cloned from github yesterday.
Here is the output of the script (I added the debug flag to gphoto2).
[sony-pm-alt-log.txt](https://github.com/falk0069/sony-pm-alt/files/77519/sony-pm-alt-log.txt)

Does this mean something to you?

Thanks for your help.
Nicolas

**Comment by nicolaselie** [comment]
Sorry, my mistake. I installed the last version of gphoto2 but not for libgphoto2.
It is now working very well.

I also wanted to let you know that I didn't find the key in the registry with the GUID. Had to use wireshark.
I'm closing the ticket.

**Comment by falk0069** [comment]
I'm glad to hear the feedback and excited it worked for you with the latest gphoto2.
