### ISSUE TITLE
android app protocol (http+xml)

### ISSUE THREAD

**Issue by r00t-** [falk0069/sony-pm-alt#27]
hello,
i recently tried to use your code, but was put off by the complexity of the linking process,
and by the fact that i had never used the play memories desktop program,
but the "PlayMemories Mobile" android app.
i captured the traffic between the android app and the camera (using tcpdump on a rooted phone),
looking for the ID required for linking,
but instead discovered that the app uses a **COMPLETELY DIFFERENT protocol**.
it's based on http and xml (soap), and while it's rather convoluted (as xml protocols typically are),
it's 100% human readable, and it works just fine to download images.

example and the most important requests:
[ select "send to smartphone" on the camera, connect to wifi ]
(the ip network served by the camera is extremely disruptive, 192.168.0.0/16, so you will want to ignore the route served via dhcp and set a host-route manually: `ip addr add 192.168.0.1/32 dev <interface> ; route add -host 192.168.122.1 <interface>`. the IP seems to always be the same.)

retrieve some info:
```
$ curl http://192.168.122.1:64321/DigitalImagingDesc.xml
$ curl http://192.168.122.1:64321/DmsDescPush.xml
```
to display the "Sending" screen:
```
$ curl -XPOST http://192.168.122.1:64321/upnp/control/XPushList --header 'SOAPACTION: "urn:schemas-sony-com:service:XPushList:1#X_TransferStart"' --header 'Content-Type: text/xml; charset="utf-8"' -d '<?xml version="1.0" encoding= "UTF-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:X_TransferStart xmlns:u="urn:schemas-sony-com:service:XPushList:1"></u:X_TransferStart></s:Body></s:Envelope>'
```

to retrieve the list of images:
```
$ curl -XPOST http://192.168.122.1:64321/upnp/control/ContentDirectory --header 'SOAPACTION: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"' --header 'Content-Type: text/xml; charset="utf-8"' -d '<?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><ObjectID>PushRoot</ObjectID><BrowseFlag>BrowseDirectChildren</BrowseFlag><Filter>*</Filter><StartingIndex>0</StartingIndex><RequestedCount>9999</RequestedCount><SortCriteria></SortCriteria></u:Browse></s:Body></s:Envelope>' | xmlstarlet sel -T -t -v //Result | xmlstarlet fo
```
(the response contains http download urls.)

**Comment by jumpjack** [comment]
Any idea about the protocol used to control [pan/tilt mounts](https://www.amazon.it/-/en/YT-260-Motorized-Camera-Swivel-Control/dp/B07TT33QQ1/ref=pd_lpo_4?pd_rd_w=PAzKv&content-id=amzn1.sym.992f08af-eb2a-4a7b-90a4-cd77032caf05&pf_rd_p=992f08af-eb2a-4a7b-90a4-cd77032caf05&pf_rd_r=Z0192CCABF6GS1HN48MR&pd_rd_wg=eeh7Q&pd_rd_r=a56d929d-87c9-4f25-9196-ed0e9ee538c6&pd_rd_i=B07TT33QQ1&psc=1)?

![image](https://user-images.githubusercontent.com/1620953/222373635-dc23a146-dbe3-4175-8934-06dd783b7ac3.png)



> 【Controllo APP e telecomando】 - Insieme all'APP per il controllo remoto della fotocamera nel telefono cellulare, puoi scattare foto e video sul tuo telefono cellulare e la testa panoramica può aiutare la fotocamera a trovare l'oggetto. Software di controllo remoto del telefono cellulare per YT-26PLAYMEMORIES. Inclinazione, il telecomando del telefono cellulare può aiutarti a riprendere video o foto per GOPRO entro 20 metri. Dotato di un telecomando separato.

**Comment by schorschii** [comment]
Hi @r00t-!

Thanks for the hint with the SOAP API used by the mobile apps. This API seems way easier to use (no PTP-GUID necessary). I wrote a small script which downloads all images from this API: [ImagingEdge4Linux](https://github.com/schorschii/ImagingEdge4Linux).

Feedback is highly appreciated.

**Comment by r00t-** [comment]
@schorschii:
nice to see somebody putting this to use!
did you do any further reverse-engineering of your own? (because your readme mentions reverse engineering. - yet the only new thing i see in your code is the transfer-end command.)

what i was looking to implement would be a program that runs in the background and automatically detecting the camera in push mode, connecting, retrieveing, disconnecting, so on can leave the phone in the pocket (or computer in the backpack), not having to operate two devices simultaneously.
(the main reason i started looking at this is because the sony app is not only annoying to operate but also unreliable, often taking many attempts to get a successful transfer.)

**Comment by schorschii** [comment]
Yes, I dug a little further. I noticed that  `http://192.168.122.1:64321/XPlsDesc.xml` shows possible API calls, so I tried the `TransferProgress` command advertised there, but at least on my camera, this does nothing. (I expected a transfer progress bar on the camera display.)

I implemented a daemon mode for you. You can start the script now with the `--daemon` parameter and it will run in background and sync images as soon as the camera is reachable i.e. WiFi is connected (you can put this in your autostart). If you have questions or can confirm another working model, feel free to head over in the discussion tab of my repo :)

I'll have the chance to test this next week with an ILCA-99.

**Comment by r00t-** [comment]
tested and posted on your project's tracker.
