### ISSUE TITLE
setsockopt error: Invalid argument

### ISSUE THREAD

**Issue by krulkrul** [falk0069/sony-pm-alt#3]
Hi,

At time of starting the python script I got a socket error, see below. Any idea why? Perhaps i did not setup the config well:

BCAST_IP = "192.168.1.255" #not sure about this, should this the camera IP, or the broadcast IP which I took from ifconfig? I tried both but neither are working
UPNP_PORT = 1900 #I left this to the default

```
2016-02-21 15:53:42,217 [INFO ] Server starting
2016-02-21 15:53:42,219 [ERROR] setsockopt error: Invalid argument
2016-02-21 15:53:42,219 [INFO ] Waiting for connections to end before exiting
```

I manage to get the GUID through wireshark, only last 3 bytes are different with your example. Hope to get this part working. Thanks a lot.

**Comment by krulkrul** [comment]
Just after writing this post I gave the default value a try which seems to work. Not sure what this IP address is, but I will close this 'issue'....

**Comment by krulkrul** [comment]
Seems it is not correct after all; it is now in a loop that it re-writes the gphoto config file. Looks like the port won't set correctly:  `gphoto2=port=usb:001,001`

```
2016-02-21 16:14:36,200 [INFO ] received MtpNullService from ('192.168.1.79', 1900)
2016-02-21 16:14:36,204 [INFO ] Starting new HTTP connection (1): 192.168.1.79
2016-02-21 16:14:36,212 [INFO ] Creating backup: ~/.gphoto/settings.20160221161436.bak
2016-02-21 16:14:36,214 [INFO ] New settings written to ~/.gphoto/settings
Skip existing file README.txt  
```

**Comment by falk0069** [comment]
Hi krulkrul,

Sorry I haven't responded--I was out of town for a while.  For the BCAST IP you will want to leave it 239.255.255.250.  This is standard multicast address that UPNP uses.  Check out this Wiki: 
https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol

For your GUID, did you generate that from a VirtualBox Windows?  I think it is derived from the MAC address and I think VirtualBox starts all MAC addresses the same and only the last few bytes are different.  So, that would make sense if you used VirtualBox.

Let me know if you've made any progress.

Thanks

**Comment by krulkrul** [comment]
Hi falk0069,

Indeed I used VirtualBox so that explains the MAC address. But I was not able to get around the issue that the gphoto config file is constantly being updated. It basically goes into an loop as it see the config file is not correct but is not updating it correctly with the IP address. Any ideas?

**Comment by falk0069** [comment]
That is odd.  The script only updates the file if there is a change.  And this should only happen if you change the PTP_GUID or if the Camera's IP Address changed.  I could see the IP Address changing occasionally but not every time.  I'm wondering if there is some sort of newline character that is throwing things off.

Can you run a 'diff' between the current and a backup file?  For example:
diff ~/.gphoto/settings ~/.gphoto/settings.20150302*.bak

I'm curious what might be triggered as being different if anything.

Another thing to try is starting the script with the debug flag:
./sony-pm-alt.py -d

If you want to provide a clip of the log, I'll see if I can spot anything.

**Comment by falk0069** [comment]
Another idea I had is it might be gphoto that is updating the settings file.  The curious thing is the <code>usb:001,001</code> you posted.  When you are testing this, is the camera plugged in via USB?  Hopefully you want to do everything wirelessly, right?

Maybe what you should first try is just running gphoto right after you select the 'send to computer' option.  Try just running this and see if it does anything:
```
gphoto2 --port ptpip:192.168.1.79 --summary
```

You could even try this to download pictures and see if it works:
```
gphoto2 --port ptpip:192.168.1.79 -P --skip-existing
```

If you can get gphoto to work, the python script be easy to figure out.  All it really does is listen for the 'send to computer' broadcast and kicks off gphoto.  

Let me know how it goes.

**Comment by krulkrul** [comment]
gphoto2 itself works (both the summary and the actual download).

It seems really the settings file which is not written correctly, somehow the USB is in there, while debug message indicates the right ip address. btw the camera is not connected via USB.

One other strange thing is the message about the README.txt, is the script looking at the wrong directory/files?


```
Skip existing file README.txt                                                  
2016-03-05 11:49:25,697 [INFO ] received MtpNullService from ('192.168.1.79', 1900)
2016-03-05 11:49:25,697 [DEBUG]  data:
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=1800
LOCATION: http://192.168.1.79:1900/DeviceDescription.xml
NT: urn:microsoft-com:service:MtpNullService:1
NTS: ssdp:alive
SERVER: FedoraCore/2 UPnP/1.0 MINT-X/1.8.1
USN: uuid:00000000-0001-0010-8000-00aefa61ec96::urn:microsoft-com:service:MtpNullService:1
2016-03-05 11:49:25,698 [INFO ] Starting new HTTP connection (1): 192.168.1.79
2016-03-05 11:49:25,706 [DEBUG] "GET /DeviceDescription.xml HTTP/1.1" 200 1367
2016-03-05 11:49:25,708 [DEBUG] Got XML - verify if our camera
2016-03-05 11:49:25,709 [DEBUG] Camera Found...starting gphoto
2016-03-05 11:49:25,709 [DEBUG] New settings file needed
2016-03-05 11:49:25,710 [INFO ] Creating backup: ~/.gphoto/settings.20160305114925.bak
2016-03-05 11:49:25,714 [INFO ] New settings written to ~/.gphoto/settings
2016-03-05 11:49:25,714 [DEBUG] 
----------
gphoto2=port=ptpip:192.168.1.79
gphoto2=model=PTP/IP Camera
ptp2_ip=guid=00:00:00:00:00:00:00:00:ff:ff:08:00:27:71:9a:de
----------
2016-03-05 11:49:25,719 [DEBUG] ----------------------
2016-03-05 11:49:25,720 [DEBUG]   
Skip existing file README.txt    
```   

When I terminate the script at this point with ctrl + c I can see that the current settings file (as well as the backup files) all contain the USB identifier, not the ip address. The file permissions are ok, I can see that the file has been updated from the timestamp:

```
gphoto2=port=usb:001,001
gphoto2=model=USB PTP Class Camera
ptp2_ip=guid=00:00:00:00:00:00:00:00:ff:ff:08:00:27:71:9a:de
```

**Comment by falk0069** [comment]
It has to be something new gphoto is doing.  What is your gphoto2 and libgphoto2 version?  You can run <code>gphoto2 --version</code>.  For now what you should be able to do is override that setting by updating the args:
```
GPHOTO_CMD_ARGS = ["/path/to/gphoto2"),"--port","ptpip:192.168.1.79","-P","--skip-existing"]
```

This should work as long as your camera IP doesn't change.

For the directory where pictures get downloaded to it just takes the <code>PHOTO_DIR = </code> value and does a 'cd' to there before running.  What values are you using for this? 

What I think I'll do is download the latest gphtoto and see how it works and I'll also add a few more debug to lines to the code to help see what it is doing.

I'll let you know if I discover anything new.

**Comment by falk0069** [comment]
Issue reproduced!  It does seem that the newer versions if gphoto2 now assumes USB if you don't specify <code>--port ptpip:IP</code> on the command line.  It shouldn't be too hard to fix this and always include it.  I'll upload a new version of the code shortly.

**Comment by falk0069** [comment]
New code updated.  Hopefully you just need to update your PHOTO_DIR and PTP_GUID and you'll be set.  Excited to hear if it works for you.

**Comment by krulkrul** [comment]
Cool...new version works! It's downloading as we speak :)

Thanks a lot for looking into this and make it work.
