### ISSUE TITLE
Gphoto error

### ISSUE THREAD

**Issue by shaun-ba** [falk0069/sony-pm-alt#6]
Can't get gphoto to work at all, i'm not 100% about the ordering of the gphoto steps though to be honest.

Ubuntu 16.04, gphoto from repository, camera connected to my router successfully.

Camera shows this text when i click send to computer "Connected to the access point, cannot connect to the computer to be saved"

`0.035922 gp_port_open                (2): Opening  port...
0.035977 ptp_ptpip_connect           (2): connecting to ptpip:192.168.1.222.
connect cmd: No route to host
3.033074 camera_init [library.c:7350](0): Failed to connect.
3.033084 gp_port_close               (2): Closing port...
3.033307 gp_context_error            (0): An error occurred in the io-library ('I/O problem'): No error description available

**\* Error **\*  
An error occurred in the io-library ('I/O problem'): No error description available
**\* Error (-7: 'I/O problem') ***`

Any ideas?

**Comment by falk0069** [comment]
Are you using the python script or running the gphoto2 directly?  The error tells me that the camera's IP address is not 192.168.1.222.  However, if the python script is what triggered the gphoto2 app, then that IP should be right.  Also, were you able to get the camera linked?  

I'd recommend editing sony-pm-alt.py and setting line 19 to:
```DEBUG = True```

Then start it up and manually ```./sony-pm-alt.py``` and then start your camera and try sending the pictures.  You should get some sort of logs printed that hopefully tells you more on what is happening.

Let me know how it goes.

**Comment by falk0069** [comment]
I attempted to add a troubleshooting section to the main page.  Check it out and let me know if it helps at all.

**Comment by pauledd** [comment]
I had the same error as shaun-ba because I used the gphoto command as mentioned at "GETTING GPHOTO2" in the readme... maybe you should mention there is a ./sony-pm-alt.py to run for idiots like me ;)

**Comment by falk0069** [comment]
I added a few more comments
